Repository coveo/search-ui-extensions, pull requests merged in 2019-10, with the labels that each got.

#42 fix(SFINT-2577): Add karma-webpack-die-hard
  config/webpack.config.karma.js
  package-lock.json
  package.json
  tests/components/ResultsFilter/ResultsFilter.spec.ts
  tests/components/ViewedByCustomer/ViewedByCustomer.spec.ts
Labels: ci & tools, tests

#43 ci(SFINT-2577): Ensure Prettier run properly on UNIX.
  .prettierignore
  .prettierrc.js
  .prettierrc.json
  .travis.yml
  package.json
  src/components/UserActions/ClickedDocumentList.ts
  src/components/UserActions/QueryList.ts
  src/components/UserActions/UserActions.scss
  tests/components/UserActions/ClickedDocumentList.spec.ts
  tests/components/UserActions/QueryList.spec.ts
  tests/components/UserActions/UserActivity.spec.ts
Labels: ci & tools

#41 Call only the User Actions api when the User action button is click SFINT-2544
  src/components/UserActions/UserActions.ts
  src/models/UserProfileModel.ts
  src/rest/UserProfilingEndpoint.ts
  tests/components/UserActions/UserActions.spec.ts
  tests/models/UserProfilingModel.spec.ts
  tests/rest/UserProfilingEndpoint.spec.ts
Labels: enhancement
